sudo: false
language: python
cache:
  pip: true
matrix:
  include:
  - python: "2.7"
    env:
    - TOXENV=py27
    - NEUTRON_SOURCE=git+https://github.com/sapcc/neutron.git@stable/mitaka-m3#egg=neutron
install:
- pip install tox-travis
- curl -L https://github.com/Mic92/iana-etc/releases/download/20180420/iana-etc-20180420.tar.gz | tar xvz
- sudo mv -f iana-etc-20180420/services /etc/services
script: tox
