sudo: false
language: python
cache:
  pip: true
matrix:
  include:
  - python: "2.7"
    env:
    - TOXENV=py27
    - NEUTRON_SOURCE=git+https://github.com/sapcc/neutron.git@stable/queens-m3#egg=neutron
    - UPPER_CONSTRAINTS_FILE=https://raw.githubusercontent.com/sapcc/requirements/stable/queens-m3/upper-constraints.txt
  - python: "2.7"
    env:
    - TOXENV=pep8
    - NEUTRON_SOURCE=git+https://github.com/sapcc/neutron.git@stable/queens-m3#egg=neutron
    - UPPER_CONSTRAINTS_FILE=https://raw.githubusercontent.com/sapcc/requirements/stable/queens-m3/upper-constraints.txt
install:
- pip install tox-travis
- curl -L https://github.com/Mic92/iana-etc/releases/download/20180420/iana-etc-20180420.tar.gz | tar xvz
- sudo mv -f iana-etc-20180420/services /etc/services
script: tox
